# Use the official PHP image with Apache
FROM docker.io/php:8-apache
LABEL maintainer="craig@k5n.us"
LABEL vendor="k5n.us"

# Install mysqli extension
RUN docker-php-ext-install mysqli

# Install PosgreSQL extension and dependencies
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql

# Install GD extension and its dependencies
RUN apt-get update \
 && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libonig-dev \
        libpng-dev \
        libpng-dev \
        libzip-dev \
    && rm -rf /var/cache/apt/archives /var/lib/apt/lists/* \
    && apt-get clean \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

# Copy all files except those in .dockerignore
COPY . /var/www/html/

# Create an empty settings.php file with write permissions for anyone
# to allow the web-based installer to update it.
RUN touch /var/www/html/includes/settings.php
RUN chmod 777 /var/www/html/includes/settings.php

# Kinda of annoying not to be able to write to the filesystem via an
# editor if one doesn't exist
RUN apt-get update\
 && apt-get install -y \
         vim \
         nano \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists/* \
 && apt-get clean

# Set working directory
WORKDIR /var/www/html

# Start Apache server in the foreground
CMD ["apache2-foreground"]
